# Generated by Django 4.0.4 on 2022-10-20 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doljnosti',
            fields=[
                ('id_doljnost', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('prioritet', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sotrudniki',
            fields=[
                ('id_sotrudnik', models.AutoField(primary_key=True, serialize=False)),
                ('Code', models.IntegerField()),
                ('Stavka', models.FloatField(blank=True, default=None, null=True)),
                ('FIO', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Zadachi',
            fields=[
                ('id_zadacha', models.AutoField(primary_key=True, serialize=False)),
                ('text_zadacha', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sotrudnik_zadachi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.TextField(blank=True, default=None, null=True)),
                ('id_sotrudnik', models.ForeignKey(db_column='id_sotrudnik', on_delete=django.db.models.deletion.DO_NOTHING, to='api.sotrudniki')),
                ('id_zadacha', models.ForeignKey(db_column='id_zadacha', on_delete=django.db.models.deletion.DO_NOTHING, to='api.zadachi')),
            ],
        ),
        migrations.CreateModel(
            name='Podrazdeleniya',
            fields=[
                ('id_podrazdel', models.AutoField(primary_key=True, serialize=False)),
                ('name_podrazdel', models.TextField()),
                ('id_nachal', models.ForeignKey(blank=True, db_column='id_sotrudnik', default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.sotrudniki')),
            ],
        ),
        migrations.CreateModel(
            name='Doljnost_sotrudnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_doljnost', models.ForeignKey(db_column='id_doljnost', on_delete=django.db.models.deletion.DO_NOTHING, to='api.doljnosti')),
                ('id_sotrud', models.ForeignKey(db_column='id_sotrudnik', on_delete=django.db.models.deletion.DO_NOTHING, to='api.sotrudniki')),
            ],
        ),
    ]
